// Shadowrun skill to attribute mapping
// Key: skill name, Value: attribute name (SR5 standard)
module.exports = {
  "Archery": "AGI",
  "Armorer": "LOG",
  "Automatics": "AGI",
  "Blades": "AGI",
  "Clubs": "AGI",
  "Exotic Melee Weapon": "AGI",
  "Longarms": "AGI",
  "Pistols": "AGI",
  "Throwing Weapons": "AGI",
  "Unarmed Combat": "AGI",
  "Aeronautics Mechanic": "LOG",
  "Automotive Mechanic": "LOG",
  "Cybertechnology": "LOG",
  "Demolitions": "LOG",
  "First Aid": "LOG",
  "Forgery": "AGI",
  "Hardware": "LOG",
  "Industrial Mechanic": "LOG",
  "Medicine": "LOG",
  "Nautical Mechanic": "LOG",
  "Armorer": "LOG",
  "Artisan": "INT",
  "Disguise": "INT",
  "Escape Artist": "AGI",
  "Palming": "AGI",
  "Perception": "INT",
  "Sneaking": "AGI",
  "Survival": "WIL",
  "Tracking": "INT",
  "Con": "CHA",
  "Etiquette": "CHA",
  "Impersonation": "CHA",
  "Instruction": "CHA",
  "Intimidation": "CHA",
  "Leadership": "CHA",
  "Negotiation": "CHA",
  "Performance": "CHA",
  "Animal Handling": "CHA",
  "Navigation": "INT",
  "Pilot Aerospace": "REA",
  "Pilot Aircraft": "REA",
  "Pilot Ground Craft": "REA",
  "Pilot Watercraft": "REA",
  "Gunnery": "AGI",
  "Heavy Weapons": "AGI",
  "Throwing Weapons": "AGI",
  "Computer": "LOG",
  "Cybercombat": "LOG",
  "Data Processing": "LOG",
  "Electronic Warfare": "LOG",
  "Hacking": "LOG",
  "Software": "LOG",
  // Add more as needed
};
